# Generated by Django 4.1.2 on 2023-03-02 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0001_initial'),
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknote',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='taskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Projects.task'),
        ),
        migrations.AddField(
            model_name='taskcomments',
            name='taskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Projects.task'),
        ),
        migrations.AddField(
            model_name='taskcomments',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tickets.category'),
        ),
        migrations.AddField(
            model_name='task',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Projects.project'),
        ),
        migrations.AddField(
            model_name='projectnote',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Projects.project'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Tickets.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_by_project_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifications',
            name='projectID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Projects.project'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='taskID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Projects.task'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='ticketID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Tickets.tickets'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assigntask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_task_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assigntask',
            name='taskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Projects.task'),
        ),
        migrations.AddField(
            model_name='assigntask',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
